title: High Assurance for the Rest of Us
description: High-assurance Linux systems, logging, auditing, and tooling

theme: minima

google_analytics: G-1TXY51X8BQ

# Ensure GitHub Pages compatibility
markdown: kramdown

# Do NOT set baseurl for a user site
baseurl: ""

# Optional but useful
show_excerpts: false

header_pages:
  - posts.md
  - about.md
